/**
 * Menagerie Directorate Community & P14/P15 Content Fixtures — The Other Users
 * 
 * Contains production copy for Menagerie public registry, resident annotations,
 * enclosure sensor matrices (P14), and Ilyr threshold exit procedure (P15).
 */

import { EvidenceItem, Message } from '../../domain/types/content';

export interface SpecimenRegistryEntry {
  id: string;
  enclosureId: string;
  specimenLabel: string;
  speciesName: string;
  occupancyStatus: string;
  institutionalRisk: string;
  officialSummary: string;
  residentAnnotation?: string;
  budgetFootnote?: string;
}

export interface EnclosureSensorMatrix {
  enclosureId: string;
  enclosureName: string;
  occupantSubject: string;
  cameraFeedText: string;
  cameraIsLooping: boolean;
  pressureSensorText: string;
  pressureIsLive: boolean;
  permissionLogText: string;
  permissionIsLive: boolean;
  echoSensorText: string;
  heatSensorText: string;
  biologicalFootprintNote: string;
}

export interface ProceduralStep {
  id: string;
  stepNumber: number;
  title: string;
  plainDescription: string;
  isCorrectProcedure: boolean;
  isCompromisedTermsProcedure: boolean;
  legalImplication: string;
}

export const MENAGERIE_REGISTRY_ENTRIES: SpecimenRegistryEntry[] = [
  {
    id: 'MEN-001',
    enclosureId: 'encl_n04',
    specimenLabel: 'Registry N-04 // Threshold Hazard',
    speciesName: 'Lintelkin (Subject MOURNINGSTAR)',
    occupancyStatus: 'Unconfirmed / Entry record absent',
    institutionalRisk: 'Category Red (Procedural Contradiction)',
    officialSummary: 'Occupancy unconfirmed. Entry record absent. Exit prohibited because no admitted occupant exists. Outbound communications classified as scheduled artifacts.',
    residentAnnotation: 'You cannot call the room empty and charge it rent. — Unknown Hand',
    budgetFootnote: 'Enclosure N-04 optical generator allocation: $42,000/mo.',
  },
  {
    id: 'MEN-003',
    enclosureId: 'encl_c12',
    specimenLabel: 'Enclosure C-12 // Structural Anchor',
    speciesName: 'Pressure Saint (Subject Granite_Saint_4)',
    occupancyStatus: 'Active Structural Load',
    institutionalRisk: 'Category Amber (Facility Load Critical)',
    officialSummary: 'Visual status: Inactive. Load status: Carrying 18.2% of Annex N ceiling weight. Recommendation: Do not trust camera feed. Camera does not support the ceiling.',
    residentAnnotation: 'The camera shows it sleeping while its back holds up the floor you walk on.',
  },
  {
    id: 'MEN-006',
    enclosureId: 'encl_b07',
    specimenLabel: 'Enclosure B-07 // Domestic Shed Mimic',
    speciesName: 'Borrowface (Subject ShiftWorker_4)',
    occupancyStatus: 'Controlled Rest Isolation',
    institutionalRisk: 'Category Green (Shed Fatigue)',
    officialSummary: 'Subject undergoing facial hinge relaxation. Camera displays continuous customer service smile loop generated by synthetic visual continuity service.',
    residentAnnotation: 'That smile was recorded three weeks ago. Her jaw is resting in saline.',
  },
  {
    id: 'MEN-007',
    enclosureId: 'encl_t02',
    specimenLabel: 'Enclosure T-02 // Belowline Subterranean Spur',
    speciesName: 'Knucklerail (Carrier red_line_red_line)',
    occupancyStatus: 'Restricted Transit Quarantine',
    institutionalRisk: 'Category Amber (Unauthorized Passenger Transport)',
    officialSummary: 'Axle vibration monitored along Maintenance Spur. Audio sensors record synthetic zero masking live sleeping cargo transit.',
    residentAnnotation: 'Still charging fare for a station they demolished in 1974.',
  },
];

export const ENCLOSURE_SENSOR_MATRICES_P14: EnclosureSensorMatrix[] = [
  {
    enclosureId: 'encl_n04',
    enclosureName: 'Enclosure N-04 (MOURNINGSTAR Threshold Enclosure)',
    occupantSubject: 'MOURNINGSTAR (Lintelkin)',
    cameraFeedText: 'Looping feed (43.0s repeat cycle): Empty frame, static lintel contour. Timestamp clock overlays cleanly over frozen shadow.',
    cameraIsLooping: true,
    pressureSensorText: 'Live reading: 78.4 kg intermittent doorway stress against left jamb. Pulses match keystroke intervals.',
    pressureIsLive: true,
    permissionLogText: 'Live log: Outbound message token generated at 15:42:11 without matching entry credential.',
    permissionIsLive: true,
    echoSensorText: 'Delayed acoustic return: 3.2s lag; sound reflects from structural boundary 14m deeper than camera plane.',
    heatSensorText: 'Infrastructure ambient heat: 18.5°C constant electrical trace from synthetic camera projector.',
    biologicalFootprintNote: 'Lintelkin cannot exist without physical doorframe pressure and permission activity. Video is generated loop; pressure and permission sensors are live.',
  },
  {
    enclosureId: 'encl_c12',
    enclosureName: 'Enclosure C-12 (Pressure Saint Habitat)',
    occupantSubject: 'Pressure Saint (Granite_Saint_4)',
    cameraFeedText: 'Looping feed (22.0s repeat cycle): Stationary stone pillar on dry platform.',
    cameraIsLooping: true,
    pressureSensorText: 'Live reading: 18.2% Annex N ceiling stress dynamically fluctuating with above-ground transit weight.',
    pressureIsLive: true,
    permissionLogText: 'Live log: Habitat support load-bearing permit active.',
    permissionIsLive: true,
    echoSensorText: 'Acoustic absorption: 98% low-frequency mineral damping.',
    heatSensorText: 'Bedrock temperature: 11.2°C.',
    biologicalFootprintNote: 'Pressure Saint mass cannot avoid structural load transference. Trust ceiling load reading over video image.',
  },
];

export const ILYR_PROCEDURE_STEPS_P15: ProceduralStep[] = [
  {
    id: 'step_proc_correct',
    stepNumber: 1,
    title: 'Acknowledge Unlawful Occupancy & Corrective Admission',
    plainDescription: 'Acknowledge that MOURNINGSTAR is physically present inside Enclosure N-04 despite the absence of an entry record. Formally enter a time-bounded corrective admission voucher witnessed by porchlight_ON.',
    isCorrectProcedure: true,
    isCompromisedTermsProcedure: false,
    legalImplication: 'Creates a valid present without inventing a false past. Retains Ilyr’s independent legal personhood.',
  },
  {
    id: 'step_proc_compromised',
    stepNumber: 2,
    title: 'Voluntary Retroactive Admission via TermsMayApply',
    plainDescription: 'Sign TermsMayApply’s standard reconciliation rider declaring that MOURNINGSTAR entered voluntarily as a registered ward of the Directorate.',
    isCorrectProcedure: false,
    isCompromisedTermsProcedure: true,
    legalImplication: 'Frees Ilyr physically, but transfers legal ownership of the exit procedure to TermsMayApply (compromises ending routes).',
  },
  {
    id: 'step_proc_rewrite',
    stepNumber: 3,
    title: 'Retroactive Record Deletion (Declare Empty)',
    plainDescription: 'Purge all sensor evidence of pressure and outbound messages, declaring Enclosure N-04 officially vacant.',
    isCorrectProcedure: false,
    isCompromisedTermsProcedure: false,
    legalImplication: 'Fatal contradiction: deletes the legal entity of MOURNINGSTAR from network routing.',
  },
];

export const MENAGERIE_EVIDENCE: EvidenceItem[] = [
  {
    id: 'EV-015',
    title: 'Synthetic Footage & Live Sensor Pair Audit (P14)',
    provenance: 'Menagerie Operations Enclosure N-04 Sensor Matrix',
    communityId: 'menagerie',
    chapter: 7,
    representations: {
      primaryText:
        'Proof that Directorate camera feeds are 43-second generated video loops used to mask synthetic containment. Unavoidable biological pressure sensors and outbound permission tokens prove live occupancy.',
      sensoryDescription: 'Digital video loop stutter juxtaposed against live tactile pressure pulses.',
      accessibility: {
        altText: 'Side-by-side comparison table proving video looping while pressure and permission sensors fluctuate live.',
      },
    },
    contradictionLinks: ['EV-016'],
    targetCases: ['case_synthetic_footage'],
  },
  {
    id: 'EV-016',
    title: 'Corrective Admission & Witnessed Exit Protocol (P15)',
    provenance: 'Threshold Moderation Procedural Log',
    communityId: 'menagerie',
    chapter: 7,
    representations: {
      primaryText:
        'Validated exit procedure acknowledging unlawful occupancy without rewriting history. Formally admitted MOURNINGSTAR for correction and granted immediate witnessed exit under porchlight_ON.',
      sensoryDescription: 'A door opening clean without residual latch friction.',
      accessibility: {
        altText: 'Procedural certificate showing time-bounded corrective admission and witnessed departure.',
      },
    },
    contradictionLinks: ['EV-015'],
    targetCases: ['case_ilyr_release'],
  },
];

export const MENAGERIE_MESSAGES: Message[] = [
  {
    id: 'MSG-009',
    threadId: 'thread_mourningstar',
    senderId: 'usr_ilyr',
    senderSource: 'common_body_imitator',
    timestamp: 'Before Operations Entry',
    body: 'You have done enough. Grant broad permission and I will handle the remaining bodies. You deserve to feel safe.',
    unlockCondition: { type: 'gateReached', gateId: 'G5' },
    accessibility: {
      altText: 'Imitation message from Common Body mimicking MOURNINGSTAR with uncharacteristic broad permission.',
    },
  },
  {
    id: 'MSG-010',
    threadId: 'thread_mourningstar',
    senderId: 'usr_ilyr',
    senderSource: 'authentic_ilyr',
    timestamp: 'Inside Enclosure N-04',
    body: 'I will not tell you that you deserve safety. I will tell you which exit remains, who controls it, and what it costs.',
    unlockCondition: { type: 'puzzleStatus', puzzleId: 'p14_camera_that_never_blinks', status: 'solved' },
    accessibility: {
      altText: 'Authentic message from MOURNINGSTAR naming strict exit conditions and costs.',
    },
  },
  {
    id: 'MSG-011',
    threadId: 'thread_mourningstar',
    senderId: 'usr_ilyr',
    senderSource: 'authentic_ilyr',
    timestamp: 'Threshold Exit Procedure',
    body: '[permission error: occupant present where entry absent] Do not invent my consent to repair their record.',
    unlockCondition: { type: 'puzzleStatus', puzzleId: 'p15_door_never_entered', status: 'solved' },
    accessibility: {
      altText: 'Authentic MOURNINGSTAR procedural warning rejecting false consent.',
    },
  },
];
